### ISSUE TITLE
VerificationException OpenId.Messages.IndirectSignedResponse.GetSignedMessageParts

### ISSUE THREAD

**Issue by rcollette** [DotNetOpenAuth/DotNetOpenAuth#146]
I updated to 4.0.2.xx and I am not getting the following verification exception when the RP calls the OP server.aspx   The odd thing about this one is that a generic IDictionary is being returned rather than an array, so I'm not sure why the verificationexception occurs in this instance.

I'm also curious... can pdb files be included in nuget pacakage installs (unified in this case), so that we can get line numbers in exceptions like this?   I'm not sure that there is a way to generate a pdb file with a unified assembly anyway.

2012-05-15 10:36:28,605 (GMT-4) [5] ERROR OpenIdProviderWebForms.Global - An unhandled exception was raised. Details follow: System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.Security.VerificationException: Operation could destabilize the runtime.
   at DotNetOpenAuth.OpenId.Messages.IndirectSignedResponse.GetSignedMessageParts(Channel channel)
   at DotNetOpenAuth.OpenId.ChannelElements.ExtensionsBindingElement.GetExtensionsDictionary(IProtocolMessage message, Boolean ignoreUnsigned)
   at DotNetOpenAuth.OpenId.ChannelElements.ExtensionsBindingElement.<GetExtensions>d__a.MoveNext()
   at DotNetOpenAuth.OpenId.ChannelElements.ExtensionsBindingElement.ProcessIncomingMessage(IProtocolMessage message)
   at DotNetOpenAuth.Messaging.Channel.ProcessIncomingMessage(IProtocolMessage message)
   at DotNetOpenAuth.OpenId.ChannelElements.OpenIdChannel.ProcessIncomingMessage(IProtocolMessage message)
   at DotNetOpenAuth.Messaging.Channel.ReadFromRequest(HttpRequestBase httpRequest)
   at DotNetOpenAuth.OpenId.Provider.OpenIdProvider.GetRequest(HttpRequestBase httpRequestInfo)
   at DotNetOpenAuth.OpenId.Provider.OpenIdProvider.GetRequest()
   at DotNetOpenAuth.OpenId.Provider.ProviderEndpoint.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at ASP.server_aspx.ProcessRequest(HttpContext context) in c:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2bc34c16\58b665cd\App_Web_21a4a4kw.2.cs:line 0
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by rcollette** [comment]
I was able to workaround this issue by disabling intellitrace.   I was clued in by this discussion
http://www.telerik.com/community/forums/aspnet-mvc/general/getting-error-verificationexception-operation-could-destabilize-the-runtime.aspx

At the end of the discussion, it mentions fixing the source code using

[assembly: SecurityRules(SecurityRuleSet.Level1)]

**Comment by AArnott** [comment]
Incidentally, the PDBs _are_ included in the NuGet package that we upload to symbolsource.org. But nuget.org doesn't want symbols in packages we upload there.

I don't too much care for the `SecurityRules` revert workaround. But if you can repro with PDBs so we can get line numbers, I'll look for another workaround (I've worked around CLR bugs like this before, so I suspect I can workaround this one too). You should be able to [download packages with symbols for v4.1.3 from TeamCity](http://teamcity.dotnetopenauth.net:82/viewLog.html?buildId=2181&tab=artifacts&buildTypeId=bt69).

**Comment by AArnott** [comment]
Closing due to lack of response.
