### ISSUE TITLE
Exception: 'gzip' is not a supported encoding name.

### ISSUE THREAD

**Issue by bendras** [DotNetOpenAuth/DotNetOpenAuth#149]
Hi,
Not sure what is wrong, but every 3-rd time I get this error calling PrepareRequestUserAuthorization().
Any ideas what could be wrong?

Could not reproduce on example app.
Using Twitter OAuth.
ASP.NET MVC 3

System.ArgumentException occurred
  Message='gzip' is not a supported encoding name.
Parameter name: name
  Source=mscorlib
  ParamName=name
  StackTrace:
       at System.Globalization.EncodingTable.internalGetCodePageFromName(String name)
       at System.Globalization.EncodingTable.GetCodePageFromName(String name)
       at DotNetOpenAuth.Messaging.NetworkDirectWebResponse.GetResponseReader() in c:\BuildAgent\work\6fe1ab573d75f9ba\src\DotNetOpenAuth.Core\Messaging\NetworkDirectWebResponse.cs:line 72
       at DotNetOpenAuth.OAuth.ChannelElements.OAuthChannel.ReadFromResponseCore(IncomingWebResponse response) in c:\BuildAgent\work\6fe1ab573d75f9ba\src\DotNetOpenAuth.OAuth\OAuth\ChannelElements\OAuthChannel.cs:line 171
       at DotNetOpenAuth.Messaging.Channel.RequestCore(IDirectedProtocolMessage request) in c:\BuildAgent\work\6fe1ab573d75f9ba\src\DotNetOpenAuth.Core\Messaging\Channel.cs:line 725
       at DotNetOpenAuth.Messaging.Channel.Request(IDirectedProtocolMessage requestMessage) in c:\BuildAgent\work\6fe1ab573d75f9ba\src\DotNetOpenAuth.Core\Messaging\Channel.cs:line 520
       at DotNetOpenAuth.Messaging.Channel.Request[TResponse](IDirectedProtocolMessage requestMessage) in c:\BuildAgent\work\6fe1ab573d75f9ba\src\DotNetOpenAuth.Core\Messaging\Channel.cs:line 500
       at DotNetOpenAuth.OAuth.ConsumerBase.PrepareRequestUserAuthorization(Uri callback, IDictionary`2 requestParameters, IDictionary`2 redirectParameters, String& requestToken) in c:\BuildAgent\work\6fe1ab573d75f9ba\src\DotNetOpenAuth.OAuth.Consumer\OAuth\ConsumerBase.cs:line 249
       at DotNetOpenAuth.OAuth.WebConsumer.PrepareRequestUserAuthorization(Uri callback, IDictionary`2 requestParameters, IDictionary`2 redirectParameters) in c:\BuildAgent\work\6fe1ab573d75f9ba\src\DotNetOpenAuth.OAuth.Consumer\OAuth\WebConsumer.cs:line 60
       at ....TwitterOAuthService.RequestUserAuthorization(Int64 tenantId, Int64 userId, Uri callback, HttpContext httpContext) in C:\PROJECTS...\TwitterOAuthService.cs:line 58
  InnerException: 

Thanks,
Paul.

**Comment by AArnott** [comment]
My only guess is that somehow an HTTP request went out advertising support
for gzip encoding so the response came down gzip'd, which either DNOA
doesn't directly support, or perhaps 'gzip' as the literal in this

## particular HTTP header isn't quite up to RFC standards.

Andrew Arnott
"I [may] not agree with what you have to say, but I'll defend to the death
your right to say it." - S. G. Tallentyre

On Mon, May 28, 2012 at 7:50 AM, Paul Zaliaduonis <
reply@reply.github.com

**Comment by bendras** [comment]
Related conversation: https://dev.twitter.com/discussions/4563?page=1

**Comment by cofiem** [comment]
I've gotten this error quite a lot when trying to login to Twitter using OAuth WebConsumer.

Exception information: 
    Exception type: ArgumentException 
    Exception message: 'gzip' is not a supported encoding name.
Parameter name: name
   at System.Globalization.EncodingTable.internalGetCodePageFromName(String name)
   at System.Globalization.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at DotNetOpenAuth.Messaging.NetworkDirectWebResponse.GetResponseReader()
   at DotNetOpenAuth.OAuth.ChannelElements.OAuthChannel.ReadFromResponseCore(IncomingWebResponse response)
   at DotNetOpenAuth.Messaging.Channel.RequestCore(IDirectedProtocolMessage request)
   at DotNetOpenAuth.Messaging.Channel.Request(IDirectedProtocolMessage requestMessage)
   at DotNetOpenAuth.Messaging.Channel.Request[TResponse](IDirectedProtocolMessage requestMessage)
   at DotNetOpenAuth.OAuth.ConsumerBase.ProcessUserAuthorization(String requestToken, String verifier)
   at DotNetOpenAuth.OAuth.WebConsumer.ProcessUserAuthorization(HttpRequestBase request)
   at DotNetOpenAuth.OAuth.WebConsumer.ProcessUserAuthorization()
