### ISSUE TITLE
DotNetOpenAuth seems to be requesting a resource string that causes infinite recursion in mscorlib

### ISSUE THREAD

**Issue by cofiem** [DotNetOpenAuth/DotNetOpenAuth#159]
When I open any .cshtml file in an ASP.Net MVC 3 project, I get a 'devenv.exe - Assert Failure'.

The last call I can see that is not MS, VS or System is 'DotNetOpenAuth.Reporting.GetOrCreateOriginIdentity()'.
## 'devenv.exe - Assert Failure' pop up window contents

[Window Title]
devenv.exe - Assert Failure

[Main Instruction]
devenv.exe - Assert Failure

[Content]
Expression: [mscorlib recursive resource lookup bug]
Description: Infinite recursion during resource lookup within mscorlib.  This may be a bug in mscorlib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Security_Generic

[Expanded Information]
Stack Trace:
   at System.Environment.ResourceHelper.GetResourceStringCode(Object userDataIn)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Environment.ResourceHelper.GetResourceString(String key, CultureInfo culture)
   at System.Environment.ResourceHelper.GetResourceString(String key)
   at System.Environment.GetResourceStringLocal(String key)
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessSecurityEngine.Check(CodeAccessPermission cap, StackCrawlMark& stackMark)
   at System.Security.CodeAccessPermission.Demand()
   at System.IO.File.InternalExistsHelper(String path, Boolean checkHost)
   at Microsoft.VisualStudio.Platform.VsAppDomainManager.InnerResolveHandler(String name)
   at Microsoft.VisualStudio.Platform.VsAppDomainManager.ResolveHandler(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at System.Environment.ResourceHelper.GetResourceStringCode(Object userDataIn)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Environment.ResourceHelper.GetResourceString(String key, CultureInfo culture)
   at System.Environment.ResourceHelper.GetResourceString(String key)
   at System.Environment.GetResourceStringLocal(String key)
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessSecurityEngine.Check(CodeAccessPermission cap, StackCrawlMark& stackMark)
   at System.Security.CodeAccessPermission.Demand()
   at System.IO.File.InternalExistsHelper(String path, Boolean checkHost)
   at Microsoft.VisualStudio.Platform.VsAppDomainManager.InnerResolveHandler(String name)
   at Microsoft.VisualStudio.Platform.VsAppDomainManager.ResolveHandler(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
## Here is the full event log

Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: Infinite recursion during resource lookup within mscorlib.  This may be a bug in mscorlib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Security_Generic
Stack:
   at System.Environment.FailFast(System.String)
   at System.Environment+ResourceHelper.GetResourceStringCode(System.Object)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode, CleanupCode, System.Object)
   at System.Environment+ResourceHelper.GetResourceString(System.String, System.Globalization.CultureInfo)
   at System.Environment+ResourceHelper.GetResourceString(System.String)
   at System.Environment.GetResourceStringLocal(System.String)
   at System.Environment.GetResourceFromDefault(System.String)
   at System.Security.FrameSecurityDescriptor.CheckDemand2(System.Security.CodeAccessPermission, System.Security.PermissionToken, System.RuntimeMethodHandleInternal, Boolean)
   at System.Security.SecurityRuntime.FrameDescHelper(System.Security.FrameSecurityDescriptor, System.Security.IPermission, System.Security.PermissionToken, System.RuntimeMethodHandleInternal)
   at System.Security.CodeAccessSecurityEngine.Check(System.Object, System.Threading.StackCrawlMark ByRef, Boolean)
   at System.Security.CodeAccessSecurityEngine.Check(System.Security.CodeAccessPermission, System.Threading.StackCrawlMark ByRef)
   at System.Security.CodeAccessPermission.Demand()
   at System.IO.File.InternalExistsHelper(System.String, Boolean)
   at Microsoft.VisualStudio.Platform.VsAppDomainManager.InnerResolveHandler(System.String)
   at Microsoft.VisualStudio.Platform.VsAppDomainManager.ResolveHandler(System.Object, System.ResolveEventArgs)
   at System.AppDomain.OnAssemblyResolveEvent(System.Reflection.RuntimeAssembly, System.String)
   at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(System.String, System.Globalization.CultureInfo, System.Version, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(System.Globalization.CultureInfo, System.Threading.StackCrawlMark ByRef)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(System.Globalization.CultureInfo, System.Collections.Generic.Dictionary`2<System.String,System.Resources.ResourceSet>, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, Boolean, Boolean)
   at System.Resources.ResourceManager.GetString(System.String, System.Globalization.CultureInfo)
   at System.Environment+ResourceHelper.GetResourceStringCode(System.Object)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode, CleanupCode, System.Object)
   at System.Environment+ResourceHelper.GetResourceString(System.String, System.Globalization.CultureInfo)
   at System.Environment+ResourceHelper.GetResourceString(System.String)
   at System.Environment.GetResourceStringLocal(System.String)
   at System.Environment.GetResourceFromDefault(System.String)
   at System.Security.FrameSecurityDescriptor.CheckDemand2(System.Security.CodeAccessPermission, System.Security.PermissionToken, System.RuntimeMethodHandleInternal, Boolean)
   at System.Security.SecurityRuntime.FrameDescHelper(System.Security.FrameSecurityDescriptor, System.Security.IPermission, System.Security.PermissionToken, System.RuntimeMethodHandleInternal)
   at System.Security.CodeAccessSecurityEngine.Check(System.Object, System.Threading.StackCrawlMark ByRef, Boolean)
   at System.Security.CodeAccessSecurityEngine.Check(System.Security.CodeAccessPermission, System.Threading.StackCrawlMark ByRef)
   at System.Security.CodeAccessPermission.Demand()
   at System.IO.File.InternalExistsHelper(System.String, Boolean)
   at Microsoft.VisualStudio.Platform.VsAppDomainManager.InnerResolveHandler(System.String)
   at Microsoft.VisualStudio.Platform.VsAppDomainManager.ResolveHandler(System.Object, System.ResolveEventArgs)
   at System.AppDomain.OnAssemblyResolveEvent(System.Reflection.RuntimeAssembly, System.String)
   at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(System.String, System.Globalization.CultureInfo, System.Version, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(System.Globalization.CultureInfo, System.Threading.StackCrawlMark ByRef)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(System.Globalization.CultureInfo, System.Collections.Generic.Dictionary`2<System.String,System.Resources.ResourceSet>, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, Boolean, Boolean)
   at System.Resources.ResourceManager.GetString(System.String, System.Globalization.CultureInfo)
   at System.Environment+ResourceHelper.GetResourceStringCode(System.Object)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode, CleanupCode, System.Object)
   at System.Environment+ResourceHelper.GetResourceString(System.String, System.Globalization.CultureInfo)
   at System.Environment+ResourceHelper.GetResourceString(System.String)
   at System.Environment.GetResourceStringLocal(System.String)
   at System.Environment.GetResourceFromDefault(System.String)
   at System.Environment.GetResourceString(System.String, System.Object[])
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.LongPathFile.GetLength(System.String)
   at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.IsolatedStorage.IsolatedStorageFile)
   at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.IsolatedStorage.IsolatedStorageFile)
   at DotNetOpenAuth.Reporting.GetOrCreateOriginIdentity()
   at DotNetOpenAuth.Reporting.Initialize()
   at DotNetOpenAuth.Reporting.set_Enabled(Boolean)
   at DotNetOpenAuth.Reporting..cctor()
   at DotNetOpenAuth.Reporting.get_Enabled()
   at DotNetOpenAuth.OAuthReporting.RecordFeatureAndDependencyUse(System.Object, DotNetOpenAuth.OAuth.ServiceProviderDescription, DotNetOpenAuth.OAuth.ChannelElements.ITokenManager, DotNetOpenAuth.Messaging.Bindings.INonceStore)
   at DotNetOpenAuth.OAuth.ConsumerBase..ctor(DotNetOpenAuth.OAuth.ServiceProviderDescription, DotNetOpenAuth.OAuth.ChannelElements.IConsumerTokenManager)
   at DotNetOpenAuth.OAuth.WebConsumer..ctor(DotNetOpenAuth.OAuth.ServiceProviderDescription, DotNetOpenAuth.OAuth.ChannelElements.IConsumerTokenManager)
   at EcoSounds.Mvc.Code.Logon.TwitterConsumer..ctor(DotNetOpenAuth.OAuth.ChannelElements.IConsumerTokenManager)
   at EcoSounds.Mvc.App_Start.NinjectWebCommon.RegisterServices(Ninject.IKernel)
   at EcoSounds.Mvc.App_Start.NinjectWebCommon.CreateKernel()
   at Ninject.Web.Common.Bootstrapper.Initialize(System.Func`1<Ninject.IKernel>)
   at EcoSounds.Mvc.App_Start.NinjectWebCommon.Start()
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, Boolean)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at WebActivator.BaseActivationMethodAttribute.InvokeMethod()
   at WebActivator.ActivationManager.RunActivationMethods[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]()
   at WebActivator.ActivationManager.Run()
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, Boolean)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Web.Compilation.BuildManager.InvokePreStartInitMethodsCore(System.Collections.Generic.ICollection`1<System.Reflection.MethodInfo>, System.Func`1<System.IDisposable>)
   at System.Web.Compilation.BuildManager.InvokePreStartInitMethods(System.Collections.Generic.ICollection`1<System.Reflection.MethodInfo>)
   at System.Web.Compilation.BuildManager.CallPreStartInitMethods(System.String)
   at System.Web.Compilation.BuildManager.ExecutePreAppStart()
   at System.Web.Hosting.HostingEnvironment.Initialize(System.Web.Hosting.ApplicationManager, System.Web.Hosting.IApplicationHost, System.Web.Configuration.IConfigMapPathFactory, System.Web.Hosting.HostingEnvironmentParameters, System.Security.Policy.PolicyLevel, System.Exception)
   at System.Web.Hosting.HostingEnvironment.Initialize(System.Web.Hosting.ApplicationManager, System.Web.Hosting.IApplicationHost, System.Web.Configuration.IConfigMapPathFactory, System.Web.Hosting.HostingEnvironmentParameters, System.Security.Policy.PolicyLevel)
   at System.Web.Hosting.HostingEnvironment.Initialize(System.Web.Hosting.ApplicationManager, System.Web.Hosting.IApplicationHost, System.Web.Configuration.IConfigMapPathFactory, System.Web.Hosting.HostingEnvironmentParameters, System.Security.Policy.PolicyLevel)
   at System.Web.Hosting.ApplicationManager.CreateAppDomainWithHostingEnvironment(System.String, System.Web.Hosting.IApplicationHost, System.Web.Hosting.HostingEnvironmentParameters)
   at System.Web.Hosting.ApplicationManager.CreateAppDomainWithHostingEnvironmentAndReportErrors(System.String, System.Web.Hosting.IApplicationHost, System.Web.Hosting.HostingEnvironmentParameters)
   at System.Web.Hosting.ApplicationManager.GetAppDomainWithHostingEnvironment(System.String, System.Web.Hosting.IApplicationHost, System.Web.Hosting.HostingEnvironmentParameters)
   at System.Web.Hosting.ApplicationManager.CreateObjectInternal(System.String, System.Type, System.Web.Hosting.IApplicationHost, Boolean, System.Web.Hosting.HostingEnvironmentParameters)
   at System.Web.Hosting.ApplicationManager.CreateObjectWithDefaultAppHostAndAppId(System.String, System.Web.VirtualPath, System.Type, Boolean, System.Web.Hosting.HostingEnvironmentParameters, System.String ByRef)
   at System.Web.Compilation.ClientBuildManager.CreateHost()
   at System.Web.Compilation.ClientBuildManager.EnsureHostCreated()
   at System.Web.Compilation.ClientBuildManager.GenerateCodeCompileUnit(System.String, System.String, System.Type ByRef, System.CodeDom.Compiler.CompilerParameters ByRef, System.Collections.IDictionary ByRef)
   at Microsoft.VisualStudio.Web.VsClientBuildManager.CBMCompilerParamsWorkItem.CallCBM(Microsoft.VisualStudio.Web.VsClientBuildManager.CBMThreadPool)
   at Microsoft.VisualStudio.Web.VsClientBuildManager.CBMWorkItem.Execute(Microsoft.VisualStudio.Web.VsClientBuildManager.CBMThreadPool)
   at Microsoft.VisualStudio.Web.VsClientBuildManager.CBMThreadPool.ThreadProc()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by AArnott** [comment]
Hi Mark,

Thank you for this report.  I want to forward the full repro to my
Microsoft buddies so that they can take a look.  Can you please prepare a
.zip of the smallest repro you can create so I can try to get this fixed?

Thanks.

**Comment by cofiem** [comment]
I should be able to provide a repro, but I will not have time until July.

**Comment by AArnott** [comment]
That's fine.  I look forward to hearing from you in July then.

On Wednesday, June 20, 2012, Mark wrote:

> I should be able to provide a repro, but I will not have time until July.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/AArnott/dotnetopenid/issues/159#issuecomment-6468720

## 

## 

Andrew Arnott
"I [may] not agree with what you have to say, but I'll defend to the death
your right to say it." - S. G. Tallentyre

**Comment by cofiem** [comment]
I've attempted to repro this issue in a 'as-small-as-possible' project, but I can't seem to replicate it. Seems it is dependant on the way Visual Studio builds and runs a Web Application.

**Comment by AArnott** [comment]
If you have a project of any size that repros this that you're willing to
attach to the bug (or link to) so we can repro it, I'd be happy to
investigate further.
