### ISSUE TITLE
Getting errors: Remote host closed the connection

### ISSUE THREAD

**Issue by husainshabbir** [DotNetOpenAuth/DotNetOpenAuth#17]
I am getting quite a few errors (caught by ELMAH) caused by the dotnetopenid library. The stack trace of the error is pasted below. My application is developed in ASP.NET MVC3 and is hosted on IIS7.0. Any help in resolving these would be appreciated.

```
System.Web.HttpException (0x80070057): The remote host closed the connection. The error code is 0x80070057.
   at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect)
   at System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush()
   at System.Web.HttpResponse.Flush(Boolean finalFlush)
   at System.Web.HttpResponse.End()
   at DotNetOpenAuth.Messaging.OutgoingWebResponse.Send(HttpContext context) in c:\Users\andarno\git\dotnetopenid\src\DotNetOpenAuth\Messaging\OutgoingWebResponse.cs:line 161
   at DotNetOpenAuth.Messaging.OutgoingWebResponse.Send() in c:\Users\andarno\git\dotnetopenid\src\DotNetOpenAuth\Messaging\OutgoingWebResponse.cs:line 129
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass14.<InvokeActionResultWithFilters>b__11()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)
```

**Comment by AArnott** [comment]
These exceptions are benign.  They indicate that the web visitor navigated to another page or closed their browser.  The user never saw this error.

If you want to try avoiding the exception anyway, check context.Response.IsClientConnected and only call the Send method if that property is true.
