### ISSUE TITLE
OP Endpoint(s) not in whitelist exception needed

### ISSUE THREAD

**Issue by rcollette** [DotNetOpenAuth/DotNetOpenAuth#280]
When an OP endpoint is not in the whitelist, the following exception is generated.

{DotNetOpenAuth.Messaging.ProtocolException: No OpenID endpoint found. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at DotNetOpenAuth.OpenId.RelyingParty.OpenIdRelyingParty.CreateRequest(Identifier userSuppliedIdentifier)
   --- End of inner exception stack trace ---
   at DotNetOpenAuth.OpenId.RelyingParty.OpenIdRelyingParty.CreateRequest(Identifier userSuppliedIdentifier)

This is confusing because the issue is not that the endpoint was not found but rather that the endpoint has been filtered.   I only discovered the true issue by enabling logging which yielded.

2013-05-16 11:30:31,984 (GMT-4) [6] INFO  DotNetOpenAuth.OpenId - Filtering out OP endpoint https://open.login.yahooapis.com/openid/op/auth because it is not on the exclusive trusted provider whitelist.

I would suggest that when endpoints have been filtered and no valid endpoints remain, an exception stating that the endpoints that were found were not included in the whitelist.

**Comment by vijayasarathi** [comment]
Hi even I'm facing this issue "No openid endpoint found". Can you tell me how to enable logging?
