### ISSUE TITLE
Google Apps host meta discovery fails when RequireSsl is turned on

### ISSUE THREAD

**Issue by AArnott** [DotNetOpenAuth/DotNetOpenAuth#8]
Google Apps asserts http:// claimed identifiers, but since host-meta based discovery doesn't actually ever perform an HTTP get on that identifier, RequireSsl should actually work with Google Apps discovery, provided the DNOA host meta discovery service skips the fallback discovery on the (insecure) domain itself.

The likely fix for this is for the HostMetaDiscoveryService in DotNetOpenAuth to be willing to perform discovery on insecure identifiers, but only to HTTPS trusted discovery hosts (such as Google Apps).

**Comment by ghost** [comment]
Hi Andrew, was this fixed or is there a work around? I updated to the latest version and cannot use RequireSSL in my web.config for my Google Apps implementation.

With the DotNetOpenAuth.OpenId.RelyingParty.OpenIdTextBox control, I get this error if I turn RequireSSL to on:

```
{DotNetOpenAuth.Messaging.ProtocolException: 
Sorry.  This site only accepts OpenIDs that are HTTPS-secured, but 
http://gaschool.scolab.com/openid?id=116298317018479467791 is not a secure Identifier." 
at DotNetOpenAuth.Messaging.ErrorUtilities.VerifyProtocol(Boolean condition, String message, Object[] args)
at DotNetOpenAuth.Messaging.ErrorUtilities.ThrowProtocol(String message, Object[] args)
at DotNetOpenAuth.OpenId.RelyingParty.PositiveAuthenticationResponse.VerifyDiscoveryMatchesAssertion(OpenIdRelyingParty relyingParty)
at DotNetOpenAuth.OpenId.RelyingParty.PositiveAuthenticationResponse..ctor(PositiveAssertionResponse response, OpenIdRelyingParty relyingParty)
at DotNetOpenAuth.OpenId.RelyingParty.OpenIdRelyingParty.GetResponse(HttpRequestInfo httpRequestInfo)}
```

Does this mean I have content going over an insecure channel, or just that I do not enforce such behavior?

Thanks a lot, keep the good work!
Carl

**Comment by AArnott** [comment]
No, this hasn't been fixed yet.

**Comment by ghost** [comment]
Thanks for the update. Can you tell me the security implication of turning RequireSSL to off?

Does this mean I have content going over an insecure channel, or just that I do not enforce such behavior?

Thanks!
Carl

**Comment by AArnott** [comment]
RequireSsl=false does not mean that SSL will not be used.  It merely means that DNOA will permit use of non-SSL channels if such channels are either the only option, or according to XRDS discovery considered to be the preferred option.
RequireSsl=true guarantees that only SSL channels will be used.  If your only discovery module is the HostMetaDiscoveryService one (you've removed the normal one) then you may already be set to go. If I recall correctly, the HTTPS URLs are already hard-coded, so RequireSsl=true may not offer anything new to you. Not certain, this is from memory.
